quarkus:
  log:
    category:
      "com.tomlloyd":
        level: FINE
  smallrye-openapi:
    operation-id-strategy: method
  swagger-ui:
    always-include: true
    display-operation-id: true
    theme: original
